# Generated by Django 3.0.7 on 2020-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
