# Generated by Django 3.0.7 on 2020-08-10 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0003_auto_20200804_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='likes',
            field=models.ManyToManyField(related_name='trip_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
