# Generated by Django 3.0.7 on 2020-08-10 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0004_trip_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='trip_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
