# Generated by Django 3.0.7 on 2020-09-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0006_auto_20200907_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='trip_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
