# Generated by Django 3.0.7 on 2020-09-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_auto_20200924_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='like',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
